name: FurEverHome
description: A Pet Adoption App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # ui
  bot_toast: ^4.0.4  
  lottie: ^2.3.2
  animated_text_kit: ^4.2.2
  extended_image: ^8.0.2
  smooth_page_indicator: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Foldit
      fonts:
        - asset: assets/fonts/fold_it/Foldit-Regular.ttf
          weight: 400
        - asset: assets/fonts/fold_it/Foldit-Medium.ttf
          weight: 500
        - asset: assets/fonts/fold_it/Foldit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fold_it/Foldit-Bold.ttf
          weight: 700
    - family: PlusJakartaSans
      fonts: 
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 700
